In [1]:
import numpy as np

In [5]:
array = np.array([1, 2, 3, 4, 5])

array, type(array)

(array([1, 2, 3, 4, 5]), numpy.ndarray)

In [6]:
array0D = np.array(1)
array1D = np.array([1, 2, 3])
array2D = np.array([
  [1, 2, 3],
  [4, 5, 6]
])
array3D = np.array([
  [
    [1, 2, 3],
    [4, 5, 6]
  ],
  [
    [7, 8, 9],
    [10, 11, 12]
  ]
])

array0D.ndim, array1D.ndim, array2D.ndim, array3D.ndim

(0, 1, 2, 3)

In [98]:
array = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

array.shape, array.size

((2, 3), 6)

#### Indexing

In [16]:
array = np.array([
  [1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10]
])

"4th element from the 2nd row", array[1, 3]

('4th element from the 2nd row', 9)

In [19]:
"last element from the last row", array[-1, -1]

('last element from the last row', 10)

In [20]:
array = np.array([
  [
    [1, 2, 3],
    [4, 5, 6]
  ],  
  [
    [7, 8, 9],
    [10, 11, 12]
  ]
])

"3rd element from the 2nd row in the 1st array", array[0, 1, 2]

('3rd element from the 2nd row in the 1st array', 6)

In [26]:
array = np.array([1, 2, 3, 4, 5, 6, 7])

array[1:5], array[5:], array[:5], array[-3:-1]

(array([2, 3, 4, 5]), array([6, 7]), array([1, 2, 3, 4, 5]), array([5, 6]))

In [30]:
array[1:-1:2]

array([2, 4, 6])

In [36]:
array = np.array([
  [1, 2, 3, 4, 5],
  [6, 7, 8, 9, 10]
])

array[1, 1:4], array[0:, 1:4]

(array([7, 8, 9]),
 array([[2, 3, 4],
        [7, 8, 9]]))

#### Iterate Array

In [40]:
array = np.array([1, 2, 3])

for i in array:
  print(i)

1
2
3


In [41]:
array = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

for i in array:
  for j in i:
    print(j)

1
2
3
4
5
6


In [59]:
for i in np.nditer(array):
  print(i)

1
2
3
4


#### Mathematical Operations on Array

In [51]:
array = np.array([1, 2, 3, 4])

array + 1, array * 2, array ** 2

(array([2, 3, 4, 5]), array([2, 4, 6, 8]), array([ 1,  4,  9, 16]))

In [57]:
np.power(array, 2)

array([ 1,  4,  9, 16], dtype=int32)

In [60]:
"sum of all elements of array", array.sum()

('sum of all elements of array', 10)

In [69]:
array = np.array([
  [1, 1],
  [2, 2]
])

# axis 0 is axis x (iterate the columns)
# axis 1 is axis y (iterate the rows)
array.sum(axis = 0), array.sum(axis = 1)

(array([3, 3]), array([2, 4]))

In [71]:
array1 = np.array([
  [1, 2],
  [3, 4]
])

array2 = np.array([
  [2, 1],
  [4, 3]
])

array1 == array2, np.array_equal(array1, array2)

(array([[False, False],
        [False, False]]),
 False)

#### Sort Array

In [88]:
array = np.array([5, 6, 7, 1, 8, 9, 2, 3, 4])
descending_sorting = np.sort(array)

# sorted by values, sorted by index
descending_sorting, descending_sorting[::-1]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([9, 8, 7, 6, 5, 4, 3, 2, 1]))

In [91]:
array = np.array(["Banana", "Cherry", "Apple"])

np.sort(array)

array(['Apple', 'Banana', 'Cherry'], dtype='<U6')

#### Filter Array

In [93]:
array = np.array([41, 42, 43, 44])
filter_array = [True, False, True, False]

array[filter_array]

array([41, 43])

In [94]:
array = np.array([41, 42, 43, 44])
filter_array = []

for i in array:
  filter_array.append(True if i > 42 else False)

array[filter_array]

array([43, 44])

In [95]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
filter_array = array % 2 == 0

array[filter_array]


array([2, 4, 6, 8])

#### Filter Array with `np.where`

In [ ]:
array = np.array([1, 2, 3, 4, 5, 4, 3, 2, 1])

# get element indexes that meet the condition
np.where(array == 3)

In [96]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np.where(array % 2 == 0)

(array([1, 3, 5, 7], dtype=int64),)

#### Reshape Array

In [106]:
# shape: (3, 4)
array = np.array([
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
])

array.reshape(-1), array.reshape(2, 6), array.reshape(4, 3)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))